trigger:
  - master

resources:
  containers:
    - container: android_container
      image: thejunkjon/android-introspection
      options: '--group-add root --user root'

    - container: webapp_container
      image: thejunkjon/android-introspection-webapp
      options: '--group-add root --user root'

jobs:

  - job: BuildWasm
    displayName: Build WASM
    container: webapp_container

    steps:
    - checkout: self
      submodules: true

    - script: |
        sudo chown -R 1001:1001 "/home/user/.npm"
        sudo ./dev/scripts/env.sh ai_build_wasm
      displayName: 'Build WASM'

    - script: |
        sudo ./dev/scripts/env.sh ai_build_wasm_host
      displayName: 'Build WASM Host'

    - script: |
        sudo ./dev/scripts/env.sh ai_dist_wasm
      displayName: 'Publish WASM artifacts'

  - job: BuildAndroid
    displayName: Build Android
    container: android_container

    steps:
    - checkout: self
      submodules: true

    - script: |
        sudo ./dev/scripts/env.sh ai_build_android
      displayName: 'Build Android'

  - job: BuildWebApp
    displayName: Build Web App
    container: webapp_container
    dependsOn: BuildWasm
    condition: succeeded()

    steps:
    - checkout: self
      submodules: true

    - script: |
        sudo ./dev/scripts/env.sh ai_build_webapp
      displayName: 'Build Web App'
