trigger:
  - master

resources:
  containers:
    - container: android_container
      image: thejunkjon/android-introspection

    - container: webapp_container
      image: thejunkjon/android-introspection-webapp

jobs:

  - job: BuildWasm
    displayName: Build WASM
    container: webapp_container

    steps:
    - checkout: self
      submodules: true

    - bash: ./dev/scripts/env.sh ai_build_wasm
      displayName: 'Build WASM'
      noProfile: false
      noRc: false

    - bash: ./dev/scripts/env.sh ai_build_wasm_host
      displayName: 'Build WASM Host'
      noProfile: false
      noRc: false

    - bash: ./dev/scripts/env.sh ai_dist_wasm
      displayName: 'Publish WASM artifacts'
      noProfile: false
      noRc: false

  - job: BuildAndroid
    displayName: Build Android
    container: android_container

    steps:
    - checkout: self
      submodules: true

    - bash: ./dev/scripts/env.sh ai_build_android
      displayName: 'Build Android'
      noProfile: false
      noRc: false

  - job: BuildWebApp
    displayName: Build Web App
    container: webapp_container
    dependsOn: BuildWasm
    condition: succeeded()

    steps:
    - checkout: self
      submodules: true

    - bash: ./dev/scripts/env.sh ai_build_webapp
      displayName: 'Build Web App'
      noProfile: false
      noRc: false
