trigger:
- master

resources:
 containers:
   - container: build_container
     image: thejunkjon/android-introspection
     options: --user root:root

container: build_container

steps:
- checkout: self
  submodules: true

- script: |
    ./scripts/env.sh ai_build
  displayName: 'Build'
