trigger:
  - master

resources:
  containers:
    - container: android_container
      image: thejunkjon/android-introspection

    - container: webapp_container
      image: thejunkjon/android-introspection-webapp

jobs:

  - job: BuildWasm
    displayName: Build WASM
    container: webapp_container

    steps:
    - checkout: self
      submodules: true

    - task: Bash@3
      displayName: Build WASM
      inputs:
        filePath: ./dev/scripts/env.sh ai_build_wasm
        noProfile: false
        noRc: false

    - bash: ./dev/scripts/env.sh ai_build_wasm_host
      displayName: 'Build WASM Host'

    - bash: ./dev/scripts/env.sh ai_dist_wasm
      displayName: 'Publish WASM artifacts'

  - job: BuildAndroid
    displayName: Build Android
    container: android_container

    steps:
    - checkout: self
      submodules: true

    - bash: ./dev/scripts/env.sh ai_build_android
      displayName: 'Build Android'

  - job: BuildWebApp
    displayName: Build Web App
    container: webapp_container
    dependsOn: BuildWasm
    condition: succeeded()

    steps:
    - checkout: self
      submodules: true

    - bash: ./dev/scripts/env.sh ai_build_webapp
      displayName: Build Web App
