trigger:
  - master

resources:
  containers:
    - container: wasm_container
      image: thejunkjon/android-introspection
      options: --user root:root

    - container: webapp_container
      image: thejunkjon/android-introspection-webapp
      options: --user root:root

container: wasm_container

steps:
  - checkout: self
    submodules: true

  - script: |
      ./scripts/env.sh ai_build
    displayName: 'Build Android and WASM'

  - script: |
      ./scripts/env.sh ai_dist
    displayName: 'Distribute Android and WASM'
