trigger:
  - master

resources:
  containers:
    - container: wasm_container
      image: thejunkjon/android-introspection
      options: --group-add root

    - container: webapp_container
      image: thejunkjon/android-introspection-webapp
      options: --group-add root

jobs:

  - job: BuildWasm
    displayName: Build WASM
    container: wasm_container

    steps:
    - checkout: self
      submodules: true

    - script: |
        ./dev/scripts/env.sh ai_build_wasm
      displayName: 'Build WASM'

    - script: |
        ./dev/scripts/env.sh ai_build_wasm_host
      displayName: 'Build WASM Host'

    - script: |
        ./dev/scripts/env.sh ai_dist_wasm
      displayName: 'Publish WASM artifacts'

  - job: BuildAndroid
    displayName: Build Android
    container: wasm_container

    steps:
    - checkout: self
      submodules: true

    - script: |
        ./dev/scripts/env.sh ai_build_android
      displayName: 'Build Android'

  - job: BuildWebApp
    displayName: Build Web App
    container: webapp_container
    dependsOn: BuildWasm
    condition: succeeded()

    steps:
    - checkout: self
      submodules: true

    - script: |
        ./dev/scripts/env.sh ai_build_webapp
      displayName: 'Build Web App'
