version: '3'
services:

  android:
    build:
      dockerfile: 'cm/docker/android/Dockerfile'
      context: .
    volumes:
      - '.:/ai'
    working_dir: '/ai'

  android-dev:
    build:
      dockerfile: 'cm/docker/android-dev/Dockerfile'
      context: .
    depends_on:
      - android
    volumes:
      - '.:/ai'
    working_dir: '/ai'
    tty: true
    user: $AI_UID

  web_app:
    build:
      dockerfile: 'cm/docker/web_app/Dockerfile'
      context: .
    volumes:
      - '.:/ai'
    working_dir: '/ai'

  web_app-dev:
    build:
      dockerfile: 'cm/docker/web_app-dev/Dockerfile'
      context: .
    depends_on:
      - web_app
    volumes:
      - '.:/ai'
    ports:
      - "4200:4200"
      - "9876:9876"
    working_dir: '/ai'
    tty: true
    user: $AI_UID
    command: npm --prefix=./web_app/app start
