version: '3'
services:
  android:
    build:
      dockerfile: 'cm/android/Dockerfile'
      context: .
    volumes:
      - '.:/ai'
    working_dir: '/ai'
    tty: true
    user: $AI_UID

  web_app:
    build:
      dockerfile: 'cm/web_app/Dockerfile'
      context: .
    volumes:
      - '.:/ai'
    ports:
      - "8080:4200"
    tty: true
    user: $AI_UID
    working_dir: '/ai/web_app/app'
    command: npm start