name: Build Android Introspection

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Android Introspection Project
      run: ./dev/scripts/env.sh ai_build_android
